apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: apache-struts
  labels:
    app: apache-struts
    demo: roadshow
spec:
  replicas: 2
  selector:
    app: apache-struts
  template:
    metadata:
      labels:
        app: apache-struts
    spec:
      containers:
      - name: apache-struts
        image: your-docker-repo/apache-struts:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: apache-struts-service
spec:
  selector:
    app: apache-struts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apache-struts-route
spec:
  to:
    kind: Service
    name: apache-struts-service
  port:
    targetPort: 8080
  tls:
    termination: edge
