apiVersion: v1
kind: Service
metadata:
  name: ctf-web-to-system-service
spec:
  selector:
    app: ctf-web-to-system  # This should match the labels of your pods
  ports:
    - protocol: TCP
      port: 80  # Port that the load balancer will serve on
      targetPort: 9090  # Port your application is listening on
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-web-to-system
  labels:
    app: ctf-web-to-system
    demo: roadshow
  annotation:
    app: ctf-web-to-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-web-to-system
  template:
    metadata:
      labels:
        app: ctf-web-to-system
    spec:
      containers:
      - name: ctf-web-container
        image: CHANGEME
        ports:
        - containerPort: 9090