---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    demo: roadshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/mfoster/vulnerable-demo-applications:log4shell-0.2
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
