apiVersion: v1
kind: Service
metadata:
  name: ctf-web-app-service
spec:
  selector:
    app: ctf-web-app  # This should match the labels of your pods
  ports:
    - protocol: TCP
      port: 80  # Port that the load balancer will serve on
      targetPort: 9090  # Port your application is listening on
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-web-app
  labels:
    app: ctf-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-web-app
  template:
    metadata:
      labels:
        app: ctf-web-app
    spec:
      containers:
      - name: ctf-web-container
        image: quay.io/jechoisec/ctf-web-to-system-01
        ports:
        - containerPort: 9090