apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: rocketchat
  labels:
    app: rocketchat
spec:
  replicas: 1
  selector:
    app: rocketchat
  template:
    metadata:
      labels:
        app: rocketchat
        demo: roadshow
    spec:
      containers:
        - name: rocketchat
          image: rocket.chat:2.4.9
          env:
            - name: MONGO_URL
              value: "mongodb://rocket-chat-db:27017/rocketchat"
            - name: MONGO_OPLOG_URL
              value: "mongodb://rocket-chat-db:27017/local"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-data-claim
  labels:
    placement: rocketchat-placement-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rocket-chat
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: rocket-chat
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-chat-db
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: rocketchat-db
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-chat
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: rocketchat
