apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4shell
  labels:
    demo: roadshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell
  template:
    metadata:
      labels:
        app: log4shell
    spec:
      containers:
      - name: log4shell
        image: quay.io/mfoster/vulnerable-demo-applications:log4shell-0.2
        securityContext:
          allowPrivilegeEscalation: true
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: log4shell-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: log4shell-route
spec:
  to:
    kind: Service
    name: log4shell-service
  port:
    targetPort: 80
  tls:
    termination: edge
