apiVersion: v1
kind: Service
metadata:
  name: dvga-app-service
spec:
  selector:
    app: dvga-app  # This should match the labels of your pods
  ports:
    - protocol: TCP
      port: 80  # Port that the load balancer will serve on
      targetPort: 5013  # Port your application is listening on
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvga-app
  labels:
    app: dvga-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvga-app
  template:
    metadata:
      labels:
        app: dvga-app
    spec:
      containers:
      - name: dvga-container
        image: quay.io/mfoster/vulnerable-demo-applications:damn-vulnerable-graphql-application-0.1
        workingDir: /opt/dvga
        command: ["python"]
        args: ["app.py"]
        securityContext:
          runAsUser: 1000  # Assuming UID 1000 for the 'dvga' user; adjust as necessary
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 5013