apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-dashboard-backend
  labels:
    app: metrics-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-dashboard
      component: backend
  template:
    metadata:
      labels:
        app: metrics-dashboard
        component: backend
    spec:
      containers:
        - name: backend
          image: <your-backend-image:tag>
          ports:
            - containerPort: 8000
          env:
            - name: BACKEND_PORT
              value: "8000"

---
apiVersion: v1
kind: Service
metadata:
  name: metrics-dashboard-backend
spec:
  selector:
    app: metrics-dashboard
    component: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-dashboard-frontend
  labels:
    app: metrics-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-dashboard
      component: frontend
  template:
    metadata:
      labels:
        app: metrics-dashboard
        component: frontend
    spec:
      containers:
        - name: frontend
          image: <your-frontend-image:tag>
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://metrics-dashboard-backend:8000"

---
apiVersion: v1
kind: Service
metadata:
  name: metrics-dashboard-frontend
spec:
  selector:
    app: metrics-dashboard
    component: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: metrics-dashboard-frontend
spec:
  to:
    kind: Service
    name: metrics-dashboard-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
